### ISSUE TITLE
Cannot build with rocm 5.5

### ISSUE THREAD

**Issue by eschnett** [AMReX-Codes/amrex#3337]
I cannot build AMReX 23.05 with rocm 5.5. Building with rocm 5.4 is working fine. I am seeing error messages such as

```
#0 38.13 In file included from /cactus/src/amrex-23.05/Src/Base/AMReX_DistributionMapping.cpp:3:
#0 38.13 In file included from /cactus/src/amrex-23.05/Src/Base/AMReX_MultiFab.H:8:
#0 38.13 /cactus/src/amrex-23.05/Src/Base/AMReX_FabArray.H:593:32: error: no template named 'conjunction_v' in namespace 'std'; did you mean 'Conjunction'?
#0 38.13               std::enable_if_t<std::conjunction_v<
#0 38.13                                ^~~~~~~~~~~~~~~~~~
#0 38.13                                Conjunction
```

that make me think that the compiler is somehow not using the C++17 standard. There are many other error messages that seem likewise to be caused by not using the C++17 standard.

I am configuring and building AMReX with:
```sh
    cmake \
        -DAMReX_GPU_BACKEND=HIP \
        -DAMReX_AMD_ARCH=gfx90a \
        -DAMReX_OMP=OFF \
        -DAMReX_PARTICLES=ON \
        -DAMReX_PRECISION="$precision" \
        -DBUILD_SHARED_LIBS=ON \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_C_COMPILER=/opt/rocm/llvm/bin/clang \
        -DCMAKE_CXX_COMPILER=/opt/rocm/llvm/bin/clang++ \
        -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DCMAKE_PREFIX_PATH='/opt/rocm/lib/cmake/AMDDeviceLibs;/opt/rocm/lib/cmake/amd_comgr;/opt/rocm/lib/cmake/hip;/opt/rocm/lib/cmake/hiprand;/opt/rocm/lib/cmake/hsa-runtime64;/opt/rocm/lib/cmake/rocprim;/opt/rocm/lib/cmake/rocrand' \
        -DMPI_C_ADDITIONAL_INCLUDE_DIRS='/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include' \
        -DMPI_C_LIB_NAMES='mpi;open-rte;open-pal;hwloc' \
        -DMPI_CXX_ADDITIONAL_INCLUDE_DIRS='/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include' \
        -DMPI_CXX_LIB_NAMES='mpi_cxx;mpi;open-rte;open-pal;hwloc' \
        -DMPI_hwloc_LIBRARY=/lib/x86_64-linux-gnu/libhwloc.so \
        -DMPI_mpi_LIBRARY=/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so \
        -DMPI_mpi_cxx_LIBRARY=/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so \
        -DMPI_open-pal_LIBRARY=/lib/x86_64-linux-gnu/libopen-pal.so \
        -DMPI_open-rte_LIBRARY=/lib/x86_64-linux-gnu/libopen-rte.so \
        .. && \
    make -j$(nproc) && \
    make -j$(nproc) install && \
```

starting from the `rocm/dev-ubuntu-22.04:5.5.1` Docker image.

**Comment by WeiqunZhang** [comment]
It seems that if you use hipcc as cxx compiler, it works. It also works if we can set cxx standard explicitly.

**Comment by WeiqunZhang** [comment]
@ax3l How do you want to handle this? It seems that `target_compile_features(${AMREX_TARGET} PUBLIC cxx_std_17)` we have does not work because cmake thinks `/opt/rocm/llvm/bin/clang++` as Clang 16 uses C++17 by default. But ROCm 5.5's clang++ somehow does not. We could probably enforce it by using `target_compile_options` for HIP.

**Comment by ax3l** [comment]
Thx for the ping. I think the equivalent for HIP would be
```cmake
set_property(TARGET ${AMREX_TARGET} PROPERTY HIP_STANDARD 17)
```
(forces exactly C++17, not just >= C++17).

https://cmake.org/cmake/help/latest/prop_tgt/HIP_STANDARD.html

Still looking for the equivalent of `cxx_std_17`/`cuda_std_17` for HIP (maybe `hip_...`?):
https://cmake.org/cmake/help/latest/prop_gbl/CMAKE_CUDA_KNOWN_FEATURES.html

Yes let us use `cxx_std_17` for now.

**Comment by ax3l** [comment]
@eschnett does this help for your setup? #3355

There is a chance it does not add it even with that patch, in case it assumes the defaults are already C++17. But let us know what your test with the patch says.
