### ISSUE TITLE
CUDA error with amrex 21.01

### ISSUE THREAD

**Issue by eschnett** [AMReX-Codes/amrex#1702]
I am installing AMReX via Spack on Ubuntu 18.04. I am using the options `amrex +cuda ~fortran +openmp +particles`. This works fine with version 20.12, but does not work with version 21.01. Building AMReX itself works fine, but when I use it from the Einstein Toolkit, I receive a compile-time error that functions such as `Error_device` are undefined:
```
COMPILING CarpetX/CarpetX/src/driver.cxx
/home/eschnetter/src/CarpetX/Cactus/view/include/AMReX.H(115): error: identifier
 "Error_device" is undefined
/home/eschnetter/src/CarpetX/Cactus/view/include/AMReX.H(138): error: identifier "Warning_device" is undefined

/home/eschnetter/src/CarpetX/Cactus/view/include/AMReX.H(161): error: identifier
 "Abort_device" is undefined
/home/eschnetter/src/CarpetX/Cactus/view/include/AMReX.H(187): error: identifier "Assert_device" is undefined
                                                                               
/home/eschnetter/src/CarpetX/Cactus/view/include/AMReX_Random.H(34): error: clas
s "amrex::RandomEngine" has no member "rand_state"
/home/eschnetter/src/CarpetX/Cactus/view/include/AMReX_Random.H(34): error: identifier "curand_uniform_double" is undefined

/home/eschnetter/src/CarpetX/Cactus/view/include/AMReX_Random.H(71): error: clas
s "amrex::RandomEngine" has no member "rand_state"
/home/eschnetter/src/CarpetX/Cactus/view/include/AMReX_Random.H(71): error: identifier "curand_normal_double" is undefined

/home/eschnetter/src/CarpetX/Cactus/view/include/AMReX_Random.H(107): error: cla
ss "amrex::RandomEngine" has no member "rand_state"
/home/eschnetter/src/CarpetX/Cactus/view/include/AMReX_Random.H(107): error: identifier "curand_poisson" is undefined

/home/eschnetter/src/CarpetX/Cactus/view/include/AMReX_Random.H(151): warning: v
ariable "rand" is used before its value is set
/home/eschnetter/src/CarpetX/Cactus/configs/sim/build/CarpetX/driver.cxx(107): w
arning: missing return statement at end of non-void function "CarpetX::get_group_checkpoint_flag"

/home/eschnetter/src/CarpetX/Cactus/configs/sim/build/CarpetX/driver.cxx(128): 
/home/eschnetter/src/CarpetX/Cactus/configs/sim/build/CarpetX/driver.cxx(128): warning: missing return statement at end of non-void function "CarpetX::get_group_restrict_flag"

/home/eschnetter/src/CarpetX/Cactus/configs/sim/build/CarpetX/driver.cxx(536): warning: variable "apply_physbc" was declared but never referenced

10 errors detected in the compilation of "/home/eschnetter/src/CarpetX/Cactus/configs/sim/build/CarpetX/driver.cxx".
/home/eschnetter/src/CarpetX/Cactus/configs/sim/config-data/make.config.rules:315: recipe for target 'driver.cxx.o' failed
make[3]: *** [driver.cxx.o] Error 1
```

Are there any changes e.g. to the configuration mechanism or the include file structure that could explain this? It seems that the file `AMReX.H` should include all its necessary dependencies so that there are no call of undefined functions.

**Comment by WeiqunZhang** [comment]
Can you post `/home/eschnetter/src/CarpetX/Cactus/view/include/AMReX_Config.H` here?

**Comment by eschnett** [comment]
```
#ifndef AMREX_CONFIG_H_
#define AMREX_CONFIG_H_
#define AMREX_GIT_VERSION "21.01.0"
#define AMREX_XSDK
/* #undef AMREX_DEBUG */
/* #undef AMREX_PROFILING */
/* #undef BL_PROFILING */
/* #undef AMREX_TRACE_PROFILING */
/* #undef BL_TRACE_PROFILING */
/* #undef AMREX_COMM_PROFILING */
/* #undef BL_COMM_PROFILING */
/* #undef AMREX_TINY_PROFILING */
/* #undef AMREX_MEM_PROFILING */
/* #undef AMREX_TESTING */
#define AMREX_USE_MPI
#define BL_USE_MPI
/* #undef AMREX_MPI_THREAD_MULTIPLE */
#define AMREX_USE_OMP
#define BL_USE_OMP
/* #undef AMREX_USE_DPCPP */
/* #undef AMREX_USE_FLOAT */
/* #undef AMREX_SINGLE_PRECISION_PARTICLES */
/* #undef BL_USE_FLOAT */
#define AMREX_SPACEDIM 3
#define BL_SPACEDIM 3
/* #undef AMREX_USE_ASSERTION */
/* #undef BL_FORT_USE_UNDERSCORE */
/* #undef BL_FORT_USE_LOWERCASE */
/* #undef BL_FORT_USE_UPPERCASE */
#define BL_NO_FORT
/* #undef BL_USE_SENSEI_INSITU */
/* #undef AMREX_USE_CONDUIT */
/* #undef AMREX_USE_ASCENT */
/* #undef AMREX_USE_EB */
/* #undef AMREX_USE_CUDA */
/* #undef AMREX_USE_HIP */
/* #undef AMREX_USE_NVML */
/* #undef AMREX_GPU_MAX_THREADS */
/* #undef AMREX_USE_ACC */
/* #undef AMREX_USE_GPU */
/* #undef BL_COALESCE_FABS */
/* #undef AMREX_GPUS_PER_SOCKET */
/* #undef AMREX_GPUS_PER_NODE */
#define AMREX_PARTICLES
/* #undef AMREX_USE_HDF5 */
/* #undef AMREX_USE_HDF5_ASYNC */
/* #undef AMREX_USE_HYPRE */
/* #undef AMREX_USE_PETSC */
#ifdef __cplusplus
#ifndef __GNUC__
static_assert(false,"libamrex was built with GNU. To avoid this error, reconfigure with -DAMReX_DIFFERENT_COMPILER=ON");
#endif

#endif
#if defined(AMREX_USE_OMP) && !defined(_OPENMP)
#error "libamrex was built with OpenMP, so the downstream project must activate it, too"
#endif
#endif
```

**Comment by eschnett** [comment]
```
#ifndef AMREX_CONFIG_H_
#define AMREX_CONFIG_H_
#define AMREX_GIT_VERSION "21.01.0"
#define AMREX_XSDK
/* #undef AMREX_DEBUG */
/* #undef AMREX_PROFILING */
/* #undef BL_PROFILING */
/* #undef AMREX_TRACE_PROFILING */
/* #undef BL_TRACE_PROFILING */
/* #undef AMREX_COMM_PROFILING */
/* #undef BL_COMM_PROFILING */
/* #undef AMREX_TINY_PROFILING */
/* #undef AMREX_MEM_PROFILING */
/* #undef AMREX_TESTING */
#define AMREX_USE_MPI
#define BL_USE_MPI
/* #undef AMREX_MPI_THREAD_MULTIPLE */
#define AMREX_USE_OMP
#define BL_USE_OMP
/* #undef AMREX_USE_DPCPP */
/* #undef AMREX_USE_FLOAT */
/* #undef AMREX_SINGLE_PRECISION_PARTICLES */
/* #undef BL_USE_FLOAT */
#define AMREX_SPACEDIM 3
#define BL_SPACEDIM 3
/* #undef AMREX_USE_ASSERTION */
/* #undef BL_FORT_USE_UNDERSCORE */
/* #undef BL_FORT_USE_LOWERCASE */
/* #undef BL_FORT_USE_UPPERCASE */
#define BL_NO_FORT
/* #undef BL_USE_SENSEI_INSITU */
/* #undef AMREX_USE_CONDUIT */
/* #undef AMREX_USE_ASCENT */
/* #undef AMREX_USE_EB */
/* #undef AMREX_USE_CUDA */
/* #undef AMREX_USE_HIP */
/* #undef AMREX_USE_NVML */
/* #undef AMREX_GPU_MAX_THREADS */
/* #undef AMREX_USE_ACC */
/* #undef AMREX_USE_GPU */
/* #undef BL_COALESCE_FABS */
/* #undef AMREX_GPUS_PER_SOCKET */
/* #undef AMREX_GPUS_PER_NODE */
#define AMREX_PARTICLES
/* #undef AMREX_USE_HDF5 */
/* #undef AMREX_USE_HDF5_ASYNC */
/* #undef AMREX_USE_HYPRE */
/* #undef AMREX_USE_PETSC */
#ifdef __cplusplus
#ifndef __GNUC__
static_assert(false,"libamrex was built with GNU. To avoid this error, reconfigure with -DAMReX_DIFFERENT_COMPILER=ON");
#endif

#endif
#if defined(AMREX_USE_OMP) && !defined(_OPENMP)
#error "libamrex was built with OpenMP, so the downstream project must activate it, too"
#endif
#endif
```

**Comment by eschnett** [comment]
I see the line
```
/* #undef AMREX_USE_CUDA */
```
which is wrong. I checked Spack's logs, and the configure ares were
```
-DUSE_XSDK_DEFAULTS=ON -DAMReX_SPACEDIM:STRING=3 -DBUILD_SHARED_LIBS:BOOL=ON -DAMReX_MPI:BOOL=ON -DAMReX_OMP:BOOL=ON -DXSDK_PRECISION:STRING=DOUBLE -DXSDK_ENABLE_Fortran:BOOL=OFF -DAMReX_FORTRAN_INTERFACES:BOOL=OFF -DAMReX_EB:BOOL=OFF -DAMReX_LINEAR_SOLVERS:BOOL=ON -DAMReX_AMRDATA:BOOL=OFF -DAMReX_PARTICLES:BOOL=ON -DAMReX_HDF5:BOOL=OFF -DAMReX_HYPRE:BOOL=OFF -DAMReX_PETSC:BOOL=OFF -DAMReX_CUDA:BOOL=ON
```

**Comment by drummerdoc** [comment]
Are all those camelcase args correct?

**Comment by sayerhs** [comment]
@eschnett Recently CMake got updated to use `AMReX_GPU_BACKEND=CUDA` instead of `AMReX_CUDA=ON` (see [docs](https://amrex-codes.github.io/amrex/docs_html/BuildingAMReX.html#customization-options)) ... it appears that spack's amrex/package.py has not caught up yet. You will want to `spack edit amrex` and change this to get this working, while @mic84 submits a PR to update spack.

**Comment by ax3l** [comment]
@eschnett @mic84 did we update this (xref?) and can we close this? :)

**Comment by eschnett** [comment]
This issue does not exist any more. I am using 21.04 without problems.
