### ISSUE TITLE
compilation failure with PGI+CUDA on Summit due to recent change

### ISSUE THREAD

**Issue by zingale** [AMReX-Codes/amrex#647]
The change d7371e67c896df7bdc73e3fd17550cf0d0f8da3b makes Castro no longer compile on Summit using PGI 19.10 + CUDA 10.1.168, giving:
```
/ccs/home/zingale/AMReX/Src/Base/AMReX_Utility.H(38): error: a constexpr function cannot have a nonliteral return type "void"
```

If I use the hash just before that change I can compile fine.

**Comment by WeiqunZhang** [comment]
`constexpr void` is acutally a C++14 feature.  I just removed `constexpr`.  It should work now.

**Comment by zingale** [comment]
yes, this is fixed now.  Thanks.
