### PR TITLE
CI: macOS Shared Lib

### LINKED ISSUE #425: Problem building AMReX as a shared library with CMake on MacOS
When trying to build AMReX as a **shared library** on **MacOS**, I am getting a compilation error ; the same error was also reported by @MaxThevenet in off-line discussion.

More precisely, when running:
```
mkdir builddir
cd builddir
cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DBUILD_SHARED_LIBS=ON ..
make install
```
I get
```
[100%] Linking CXX shared library libamrex.dylib
Undefined symbols for architecture x86_64:
  "getLevelBld()", referenced from:
      amrex::Amr::InitAmr()    in AMReX_Amr.cpp.o
  "_amrex_probinit", referenced from:
      amrex::Amr::readProbinFile(int&)  in AMReX_Amr.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [Src/libamrex.dylib] Error 1
make[1]: *** [Src/CMakeFiles/amrex.dir/all] Error 2
make: *** [all] Error 2
```
This error does not occur when compiling AMReX as *a static library* (i.e. removing `-DBUILD_SHARED_LIBS=ON`). Also, I am able to build AMReX as a shared library **on Ubuntu** (as opposed to MacOS).

### PR DESCRIPTION
**Pull request by ax3l**
## Summary

CI for macOS: Build a shared library. This is the default in Spack.

I see issues with AppleClang 12.0 raising:
```
ld: can't use -undefined warning or suppress with -twolevel_namespace
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

@RemiLehe reported this again here: https://github.com/AMReX-Codes/amrex/issues/425#issuecomment-473153152

- [x] reproduce issue
- [x] add fix

## Additional background

Introduced in 1b6af3cb630 to fix #425

## Checklist

The proposed changes:
- [x] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] are described in the proposed changes to the AMReX documentation, if appropriate

### CODE REVIEW

File: Tools/CMake/AMReX_Config.cmake [hunk 1]
```diff
@@ -154,11 +154,11 @@ function (configure_amrex)
...
       endif()
 
-      if(APPLE)
+      if(CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
         if( host_link_supported STREQUAL "NEW" ) # CMake 3.18+
-          target_link_options(amrex PUBLIC "LINKER:-undefined,warning")
+          target_link_options(amrex PUBLIC "LINKER:-undefined,dynamic_lookup")
         else()
-          target_link_options(amrex PUBLIC "-Wl,-undefined,warning")
+          target_link_options(amrex PUBLIC "-Wl,-undefined,dynamic_lookup")
```
Comment (ax3l) [inline Tools/CMake/AMReX_Config.cmake:161]: We can also explore:
```suggestion
          target_link_options(amrex PUBLIC "-Wl,-U,_amrex_probinit")
          target_link_options(amrex PUBLIC "-Wl,-U,getLevelBld()")
```

File: Tools/CMake/AMReX_Config.cmake [hunk 2]
```diff
@@ -154,11 +154,11 @@ function (configure_amrex)
         cmake_policy(GET CMP0105 host_link_supported)
       endif()
 
-      if(APPLE)
+      if(CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
         if( host_link_supported STREQUAL "NEW" ) # CMake 3.18+
-          target_link_options(amrex PUBLIC "LINKER:-undefined,warning")
+          target_link_options(amrex PUBLIC "LINKER:-undefined,dynamic_lookup")
```
Comment (ax3l) [inline Tools/CMake/AMReX_Config.cmake:159]:
```suggestion
          target_link_options(amrex PUBLIC "LINKER:-U,_amrex_probinit")
          target_link_options(amrex PUBLIC "LINKER:-U,getLevelBld()")
```

File: Tools/CMake/AMReX_Config.cmake [hunk 3]
```diff
@@ -154,11 +154,13 @@ function (configure_amrex)
         cmake_policy(GET CMP0105 host_link_supported)
       endif()
 
-      if(APPLE)
+      if(CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
         if( host_link_supported STREQUAL "NEW" ) # CMake 3.18+
-          target_link_options(amrex PUBLIC "LINKER:-undefined,warning")
+          target_link_options(amrex PUBLIC "LINKER:-U,_amrex_probinit")
+          target_link_options(amrex PUBLIC "LINKER:-U,getLevelBld()")
```
Comment (ax3l) [inline Tools/CMake/AMReX_Config.cmake]: Hm, what's your name... brackets tricky....
```suggestion
          target_link_options(amrex PUBLIC "LINKER:-U,getLevelBld")
```

File: Tools/CMake/AMReX_Config.cmake [hunk 4]
```diff
@@ -154,11 +154,13 @@ function (configure_amrex)
...
         else()
-          target_link_options(amrex PUBLIC "-Wl,-undefined,warning")
+          target_link_options(amrex PUBLIC "-Wl,-U,_amrex_probinit")
+          target_link_options(amrex PUBLIC "-Wl,-U,getLevelBld()")
```
Comment (ax3l) [inline Tools/CMake/AMReX_Config.cmake]:
```suggestion
          target_link_options(amrex PUBLIC "-Wl,-U,getLevelBld")
```

File: Tools/CMake/AMReX_Config.cmake [hunk 5]
```diff
@@ -154,11 +154,13 @@ function (configure_amrex)
         cmake_policy(GET CMP0105 host_link_supported)
       endif()
 
-      if(APPLE)
+      if(CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
         if( host_link_supported STREQUAL "NEW" ) # CMake 3.18+
-          target_link_options(amrex PUBLIC "LINKER:-undefined,warning")
+          target_link_options(amrex PUBLIC "LINKER:-U,_amrex_probinit")
+          target_link_options(amrex PUBLIC "LINKER:-U,getLevelBld")
```
Comment (ax3l) [inline Tools/CMake/AMReX_Config.cmake]: hm...
```suggestion
          target_link_options(amrex PUBLIC "LINKER:-U,_getLevelBld")
```

File: Tools/CMake/AMReX_Config.cmake [hunk 6]
```diff
@@ -154,11 +154,13 @@ function (configure_amrex)
...
         else()
-          target_link_options(amrex PUBLIC "-Wl,-undefined,warning")
+          target_link_options(amrex PUBLIC "-Wl,-U,_amrex_probinit")
+          target_link_options(amrex PUBLIC "-Wl,-U,getLevelBld")
```
Comment (ax3l) [inline Tools/CMake/AMReX_Config.cmake]:
```suggestion
          target_link_options(amrex PUBLIC "-Wl,-U,_getLevelBld")
```

File: Src/Amr/AMReX_LevelBld.H [hunk 7]
```diff
@@ -74,6 +74,6 @@ public:
 
 }
 
-extern AMREX_ATTRIBUTE_WEAK amrex::LevelBld* getLevelBld ();
+extern amrex::LevelBld* getLevelBld () AMREX_ATTRIBUTE_WEAK;
```
Comment (ax3l) [inline Src/Amr/AMReX_LevelBld.H:77]: Maybe like this?
```suggestion
#ifdef __cplusplus
extern "C"
{
#endif
    amrex::LevelBld* getLevelBld () AMREX_ATTRIBUTE_WEAK;
#ifdef __cplusplus
}
#endif
```

**Comment by ax3l** [comment]
Dang, what's the symbol name so I can put it on the command line to the linker
```
Undefined symbols for architecture x86_64:
  "getLevelBld()", referenced from:
      amrex::Amr::InitAmr() in AMReX_Amr.cpp.o
ld: symbol(s) not found for architecture x86_64
```

Tried so many variants now, probably need to mangle it or so.

File: Src/Amr/AMReX_LevelBld.H [hunk 8]
```diff
@@ -74,6 +74,13 @@ public:
...
 
-extern AMREX_ATTRIBUTE_WEAK amrex::LevelBld* getLevelBld ();
+#ifdef __cplusplus
+extern "C"
+{
+#endif
+    amrex::LevelBld* getLevelBld () AMREX_ATTRIBUTE_WEAK;
+#ifdef __cplusplus
+}
+#endif
```
Comment (ax3l) [inline Src/Amr/AMReX_LevelBld.H]: revert:
```suggestion
extern amrex::LevelBld* getLevelBld () AMREX_ATTRIBUTE_WEAK;
```

File: Tools/CMake/AMReX_Config.cmake [hunk 9]
```diff
@@ -154,11 +154,13 @@ function (configure_amrex)
         cmake_policy(GET CMP0105 host_link_supported)
       endif()
 
-      if(APPLE)
+      if(CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
         if( host_link_supported STREQUAL "NEW" ) # CMake 3.18+
-          target_link_options(amrex PUBLIC "LINKER:-undefined,warning")
+          target_link_options(amrex PUBLIC "LINKER:-U,_amrex_probinit")
+          target_link_options(amrex PUBLIC "LINKER:-U,_getLevelBld")
```
Comment (ax3l) [inline Tools/CMake/AMReX_Config.cmake]: Mangle like a robot:
```suggestion
          target_link_options(amrex PUBLIC "LINKER:-U,_Z11getLevelBldv")
```
https://en.wikipedia.org/wiki/Name_mangling#How_different_compilers_mangle_the_same_functions

File: Tools/CMake/AMReX_Config.cmake [hunk 10]
```diff
@@ -154,11 +154,13 @@ function (configure_amrex)
...
         else()
-          target_link_options(amrex PUBLIC "-Wl,-undefined,warning")
+          target_link_options(amrex PUBLIC "-Wl,-U,_amrex_probinit")
+          target_link_options(amrex PUBLIC "-Wl,-U,_getLevelBld")
```
Comment (ax3l) [inline Tools/CMake/AMReX_Config.cmake]:
```suggestion
          target_link_options(amrex PUBLIC "-Wl,-U,_Z11getLevelBldv")
```

File: Tools/CMake/AMReX_Config.cmake [hunk 11]
```diff
@@ -154,11 +154,13 @@ function (configure_amrex)
         cmake_policy(GET CMP0105 host_link_supported)
       endif()
 
-      if(APPLE)
+      if(CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
         if( host_link_supported STREQUAL "NEW" ) # CMake 3.18+
-          target_link_options(amrex PUBLIC "LINKER:-undefined,warning")
+          target_link_options(amrex PUBLIC "LINKER:-U,_amrex_probinit")
+          target_link_options(amrex PUBLIC "LINKER:-U,_Z11getLevelBldv")
```
Comment (ax3l) [inline Tools/CMake/AMReX_Config.cmake]: for `getLevelBld`, none of those work. Gimme the :hammer: 
```suggestion
          target_link_options(amrex PUBLIC "LINKER:-U,dynamic_lookup")
```

File: Tools/CMake/AMReX_Config.cmake [hunk 12]
```diff
@@ -154,11 +154,13 @@ function (configure_amrex)
...
         else()
-          target_link_options(amrex PUBLIC "-Wl,-undefined,warning")
+          target_link_options(amrex PUBLIC "-Wl,-U,_amrex_probinit")
+          target_link_options(amrex PUBLIC "-Wl,-U,_Z11getLevelBldv")
```
Comment (ax3l) [inline Tools/CMake/AMReX_Config.cmake]:
```suggestion
          target_link_options(amrex PUBLIC "-Wl,-U,dynamic_lookup")
```

**Review by WeiqunZhang — APPROVED** [review]
