### PR TITLE
update hiprand header path

### PR DESCRIPTION
**Pull request by pramenku**
## Need to update hiprand header path to "<hiprand/hiprand.hpp>" so it will work with future rocm release. It will work with 5.4 release too. So to be ready well ahead with future rocm changes, requesting the change,

In file included from /home/master/amr-wind/submods/amrex/Src/Base/AMReX_RandomEngine.H:11:
/opt/rocm-xxxx/include/hiprand.hpp:16:2: error: "This file is deprecated. Use the header file from /opt/rocm-xxx/include/hiprand/hiprand.hpp by using #include <hiprand/hiprand.hpp>"
#error "This file is deprecated. Use the header file from /opt/rocm-xxxx/include/hiprand/hiprand.hpp by using #include <hiprand/hiprand.hpp>"
 ^

The proposed changes: It will help user to be ready to use future rocm release alongwith previous releases like 5.4.

### CODE REVIEW

**Comment by pramenku** [comment]
hi @WeiqunZhang Can someone help to get this change merged. Thanks

**Comment by WeiqunZhang** [comment]
@pramenku Thanks for the contribution! I have also tested it on rocm/5.1. It works with both cmake and gnu make.

**Review by WeiqunZhang — APPROVED** [review]

**Comment by pramenku** [comment]
Thanks @WeiqunZhang for quick help.

Can you please point me to the person who can help with https://github.com/Exawind/amr-wind/issues/820
