### PR TITLE
NVCC 11.2: CUDA/C++17

### PR DESCRIPTION
**Pull request by ax3l**
## Summary

This adds CI coverage for C++17 builds with NVCC. Several apps expressed interest to transition to C++17 code-bases in the near future and this adds test coverage.

It is also a demonstrator for a currently failing build with NVCC 11.2 and CUDA/C++17 of AMReX.

## Additional background

Current compile error:
```
/home/runner/work/amrex/amrex/Src/Particle/AMReX_ParticleLocator.H:144:342:   required from ‘void amrex::ParticleLocator<Bins>::build(const amrex::BoxArray&, const amrex::Geometry&) [with Bins = amrex::DenseBins<amrex::Box>]’
/tmp/tmpxft_00002f17_00000000-6_AmrLevelAdv.cudafe1.stub.c:12:675:   required from here
nvcc_internal_extended_lambda_implementation:779:77: error: ‘operator()’ is not a member of ‘amrex::IntVect (amrex::ParticleLocator<Bins>::build(const amrex::BoxArray&, const amrex::Geometry&) [with Bins = amrex::DenseBins<amrex::Box>]::<lambda(const amrex::Box&)>::*)(const amrex::Box&) const noexcept’
/home/runner/work/amrex/amrex/Src/Particle/AMReX_ParticleLocator.H: In instantiation of ‘void amrex::ParticleLocator<Bins>::build(const amrex::BoxArray&, const amrex::Geometry&) [with Bins = amrex::DenseBins<amrex::Box>]’:
/tmp/tmpxft_00002f17_00000000-6_AmrLevelAdv.cudafe1.stub.c:12:675:   required from here
/home/runner/work/amrex/amrex/Src/Particle/AMReX_ParticleLocator.H:144:342: error: no matching function for call to ‘__nv_hdl_create_wrapper_t<false, false, __nv_dl_tag<void (amrex::ParticleLocator<amrex::DenseBins<amrex::Box> >::*)(const amrex::BoxArray&, const amrex::Geometry&), &amrex::ParticleLocator<amrex::DenseBins<amrex::Box> >::build, 2>, amrex::IntVect, amrex::IntVect>::__nv_hdl_create_wrapper(amrex::ParticleLocator<Bins>::build(const amrex::BoxArray&, const amrex::Geometry&) [with Bins = amrex::DenseBins<amrex::Box>]::<lambda(const amrex::Box&)>, amrex::IntVect&, amrex::IntVect&)’
  144 |         m_bins.build(num_boxes, boxes_ptr, bins_box,
      |                                                 ~~~~                                                                                                                                                                                                                                                                                                 ^
  145 |                      [=] AMREX_GPU_HOST_DEVICE (const Box& box) noexcept -> IntVect
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                   
  146 |                      {
      |                      ~                                                                                                                                                                                                                                                                                                                                
  147 |                          return (box.smallEnd() - bins_lo) / bin_size;
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                
  148 |                      });
      |                      ~                                                                                                                                                                                                                                                                                                                                
nvcc_internal_extended_lambda_implementation:798:13: note: candidate: ‘template<class Lambda> static decltype (typename __nv_hdl_helper_trait_outer<IsMutable, HasFuncPtrConv, CaptureArgs ...>::__nv_hdl_helper_trait<Tag, Lambda>::get(lam, __nv_hdl_create_wrapper_t::__nv_hdl_create_wrapper::args ...)) __nv_hdl_create_wrapper_t<IsMutable, HasFuncPtrConv, Tag, CaptureArgs>::__nv_hdl_create_wrapper(Lambda&&, CaptureArgs ...) [with Lambda = Lambda; bool IsMutable = false; bool HasFuncPtrConv = false; Tag = __nv_dl_tag<void (amrex::ParticleLocator<amrex::DenseBins<amrex::Box> >::*)(const amrex::BoxArray&, const amrex::Geometry&), &amrex::ParticleLocator<amrex::DenseBins<amrex::Box> >::build, 2>; CaptureArgs = {amrex::IntVect, amrex::IntVect}]’
nvcc_internal_extended_lambda_implementation:798:13: note:   substitution of deduced template arguments resulted in errors seen above
make[2]: Leaving directory '/home/runner/work/amrex/amrex/build'
make[2]: *** [Tutorials/Amr/Advection_AmrLevel/CMakeFiles/Tutorial_Advection_AmrLevel_SV.dir/build.make:111: Tutorials/Amr/Advection_AmrLevel/CMakeFiles/Tutorial_Advection_AmrLevel_SV.dir/Source/AmrLevelAdv.cpp.o] Error 1
```

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] are described in the proposed changes to the AMReX documentation, if appropriate

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
It seems that the compiler does not like `__host__ __device__` lambda being called from `__device__` lambda.  There are four places that are causing this issue.  In there places, they do not need to be `__host__ __device__`, so they have been changed to `__device__` only.  However, the `__host__ __device__` function in `MDParticleContainer::computeStepSize` in `Tutorials/Particles/NeighborList/MDParticleContainer.cpp` is needed to host and device because it needs to be called on both host and device.  If we comment that part out, the CI would pass.

**Comment by ax3l** [comment]
We could also make that one location a host-device functor, maybe nvcc will accept that.

**Comment by WeiqunZhang** [comment]
Can we disable that tutorial in cmake build for cuda 11?

**Comment by atmyers** [comment]
PR #1673 should let us build that tutorial with Cuda 11.

**Comment by robertmaynard** [comment]
I have found dropping the `noexcept` specifier has resolved these issues.

Specifically the `noexcept` on the host/device lambda.

**Comment by WeiqunZhang** [comment]
I guess it's related to a change in C++17 that makes `noexcept` part of function type.

**Comment by atmyers** [comment]
Thank you @robertmaynard that is a better solution: https://github.com/AMReX-Codes/amrex/pull/1674

**Review by WeiqunZhang — APPROVED** [review]
