### ISSUE TITLE
1D CUDA compilation failure due to #1332

### ISSUE THREAD

**Issue by maximumcats** [AMReX-Codes/amrex#1422]
#1332 has an issue compiling in 1D for CUDA (e.g. compiling CNS with DIM=1):

```
tmp_build_dir/s/1d.pgi.CUDA.EXE/AMReX_MultiFabUtil.cpp(221): error: duplicate parameter name

tmp_build_dir/s/1d.pgi.CUDA.EXE/AMReX_MultiFabUtil.cpp(221): error: no suitable constructor exists to convert from "amrex::Box (amrex::IntVect, amrex::IntVect)" to "amrex::Box"
```

I assume this is because the `IntVect` constructor is different in 1D but the 1D fusible kernel macro isn't quite doing the right thing in this case.
