### ISSUE TITLE
[WIP] Compile Error on Maxwell (DESY)

### ISSUE THREAD

**Issue by ax3l** [AMReX-Codes/amrex#2674]
Compiling the latest AMReX branch on [Maxwell (DESY)](https://confluence.desy.de/display/MXW/) leads to compile errors.

```
/home/diederse/software/hipace_4GPU/hipace/build/_deps/fetchedamrex-src/Src/Base/AMReX_GpuDevice.cpp(230): error: identifier "OMPI_COMM_TYPE_SOCKET" is undefined

/home/diederse/software/hipace_4GPU/hipace/build/_deps/fetchedamrex-src/Src/Base/AMReX_GpuDevice.cpp(232): error: identifier "OMPI_COMM_TYPE_NODE" is undefined
```

## Software

- OpenMPI version: 3.0 (system) or 4.1.1 (module)
- CUDA Toolkit version: 11.4.48
- Host compiler & version: GCC 9.3.0
- CMake version: 3.20.3

Note: System OpenMPI 4.1.1 module seems to be missing environment vars for `MPI_ROOT`, `PATH` and `LD_LIBRARY_PATH` (needs bug report).

## Possible Solutions

I think there might be a few things we can do in `Src/Base/AMReX_GpuDevice.cpp`:
- add the `#include <AMReX_ccse-mpi.H>` include (or `<mpi.h>`) #2675

I don't have access to the machine but @SeverinDiederichs has.

**Comment by maximumcats** [comment]
`AMReX_ParallelDescriptor.H` already includes `AMReX_ccse-mpi.H`, can you explain why #2675 would address this?

**Comment by maximumcats** [comment]
The only clear ideas I have for how this could happen are (1) a very ancient version of OpenMPI (MPI 3.0 support with OMPI_COMM_TYPE_SOCKET started in OpenMPI 2.0) or (2) this is some OpenMPI derivative which defines `OPEN_MPI` but does not implement `OMPI_COMM_TYPE_SOCKET`. The obvious sort of problems shouldn't be happening here: if `BL_USE_MPI` is defined -- which is necessary for getting into this code block -- then `mpi.h` should be included via `AMREX_ccse-mpi.H`. Also, `AMREX_GPUS_PER_SOCKET` has to be set to get here, which shouldn't be the default. So this is pretty confusing.

**Comment by ax3l** [comment]
I think there is a mismatch with the MPIs on the system going on, the OpenMPI 4.1.1 module seems to be missing environment vars for `MPI_ROOT`, `PATH` and `LD_LIBRARY_PATH` (needs bug report).

I am waiting for the user to set them manually now and if that is the culpit, report the missing vars as a module bug to system.

**Comment by maximumcats** [comment]
Can you also confirm that the user was setting GPUS_PER_SOCKET?

**Comment by ax3l** [comment]
Yep, is set.

I think it's pretty clear by now what was causing this: the system has an ancient OpenMPI 3.0 installed in system paths. The user builds with an OpenMPI 4.1.2 module that also uses a newer GCC than system.

Then an extra `hdf5-parallel` module is also loaded, which was built against the ancient system OpenMPI, leading to an incompatible software stack. Needs to be solved with system admins to provide consistent/compatible modules.
